### ISSUE TITLE
Compress/Decompress/Rename installation files for deployment

### ISSUE THREAD

**Issue by gkeuken** [zbrewdev/zbrew#100]
In order to deploy software to local or remote hosts using new HLQ we will need to Compress/Decompress/ the installation files.

Compress should be done on source system after completing all steps of the SMP/E install  (receive/apply/accept)

Decompress should be done on Target system where software will be configured. Decompress must also make use of ZBREW_TGTHLQ and thus this Issue is dependent on implementing Issue #99.

**Comment by MikeFultonDev** [comment]
this is done now
