### ISSUE TITLE
Update DDDEFs during configure/deployment

### ISSUE THREAD

**Issue by gkeuken** [zbrewdev/zbrew#101]
If ZBREW_TGTHLQ is different than ZBREW_SRCHLQ and we are deploying SMP/E environment then DDDEF's need to be updated to reflect the new HLQ.

This change is depending on #99 and #100

**Comment by MikeFultonDev** [comment]
@gkeuken  - i think i've done this. tell me if there is something still left.

**Comment by gkeuken** [comment]
This item is now obsolete as we will only perform SMP/E Actions against SRC
