### ISSUE TITLE
zbrewfuncs needs to be broken into several funcs files

### ISSUE THREAD

**Issue by MikeFultonDev** [zbrewdev/zbrew#148]
The functions file is getting large. Consider restructuring as:

zbrewfuncs:

. zbrewbasefuncs
. zbrewosfuncs 
. zbrewcicsfuncs
. zbrewimsfuncs

The various shell scripts would still just use
. zbrewfuncs
to pull everything in, but it would make it easier to work on the code

**Comment by FlappiTomic** [comment]
quick question: does the LLA and JCL stuff should go into ims? @MikeFultonDev

**Comment by FlappiTomic** [comment]
first stage is done... now need to sort out how to let sw package calls external only while zbrew calls both internal and external

**Comment by FlappiTomic** [comment]
this work will continue to a new issue, thus closing this item now.
